# Generated by Django 4.1.10 on 2023-08-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendship",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
