# Generated by Django 4.1.10 on 2023-09-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_friendship_follower_alter_friendship_following"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="friendship",
            name="unique_FollowUser",
        ),
        migrations.AddConstraint(
            model_name="friendship",
            constraint=models.UniqueConstraint(fields=("follower", "following"), name="unique_follow_user"),
        ),
    ]
